### ISSUE TITLE
v1.0.0 目标特性

### ISSUE THREAD

**Issue by ktmlm** [ktmlm/TTstack#8]
#### 网络

- 支持平面网络，类似于 flannel/vxlan 的模式，可直接访问内部实例
- [已实现] 支持 NAT 网络，访问内部实例需要经过端口转发

#### 镜像

- 镜像导入流程标准化
- 实现一个类似 DockerHub 一样的中心化镜像仓库

#### 客户端

- [已实现] 提供命令行交互工具
- 提供 Web 管理中心
- 实现更灵活的参数组合（目前是将所有标识预置在镜像名称中，以前缀匹配的方式筛选镜像）
    - 虚拟引擎类型，Firecracker、Docker、Qemu、VirtualBox ...
    - OS 类型，Linux、BSD、Windows ...
    - OS 发行版，CentOS Linux、Ubuntu Linux、FreeBSD、OpenBSD ...
    - 内核版本，rhel7-3.10.19、rhel8-4.18.1、ubuntu-4.15.4 ...

#### 服务端

- 每个虚拟引擎的实现，均添加一个 feature_check() 接口
    - 在客户端请求被执行之前，预先检测是否支持客户端请求的特性

**Comment by ccmlm** [comment]
[**redesign in process... (click me)**](https://gitee.com/kt10/ttstack/tree/feat-redesign/)
